sudo: required
services:
  - docker

before_install:
  - docker build -t rpearce63/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rpearce63/react-test npm test -- --coverage

after_success:
  - docker build -t rpearce63/multi-client ./client
  - docker build -t rpearce63/multi-nginx ./nginx
  - docker build -t rpearce63/multi-server ./server
  - docker build -t rpearce63/multi-worker ./worker

  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push rpearce63/multi-client
  - docker push rpearce63/multi-nginx
  - docker push rpearce63/multi-server
  - docker push rpearce63/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-678649654858
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
